### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by RikiRat** [WanderingCat27/Origin-Cap#1]
Can you bring it to 1.18 please?

**Comment by ChristianKilduff** [comment]
> Can you bring it to 1.18 please?

https://github.com/WanderingCat27/Origin-Cap/releases/tag/v1.4-1.18

sorry the release is not on curseforge havent updated the page in ages but here is the 1.18 version

**Comment by RikiRat** [comment]
Thank you so much your a life saver!
