### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by JTModel3** [WanderingCat27/Origin-Cap#2]
Hello! I don’t know if you are currently active anymore but I thought I would give it a shot. Is there any way that I can port it to 1.20 for use on my private server. Also do you have to cap it to 0 if you want to disable one of the origins?
Thank you!

**Comment by ChristianKilduff** [comment]
> Hello! I don’t know if you are currently active anymore but I thought I would give it a shot. Is there any way that I can port it to 1.20 for use on my private server. Also do you have to cap it to 0 if you want to disable one of the origins?
> 
> Thank you!

ive not taken a look at how it would be porting to 1.20 i cant promise u anything but ill try to take a look this weekend. Also a cap of 0 I dont recall what if 0 means locked or 0 means no cap and unlimited picks havent used my mod in a bit (or updated it)

**Comment by JTModel3** [comment]
Sounds good!

**Comment by ChristianKilduff** [comment]
ported to 1.20-1.20.1 and 1.20.2 finally had time
