### ISSUE TITLE
/origincap command isn't working

### ISSUE THREAD

**Issue by Cyther-Wuz-Taken** [WanderingCat27/Origin-Cap#7]
I'm using the 1.19 (1.4) version of the mod and i can't get any of the configs to work. the commands don't appear and there doesn't seems to be a config file either. is there a dependency I'm missing or something? I only have the default origins mod and fabric api installed along side it.

![Screenshot 2024-01-28 115207](https://github.com/WanderingCat27/Origin-Cap/assets/157980067/f254c33d-11ee-4930-a164-0c5e1eaf6ebb)
![Screenshot 2024-01-28 115249](https://github.com/WanderingCat27/Origin-Cap/assets/157980067/6a9fc781-4a02-4bc7-a7b3-60e21675df5e)

**Comment by ChristianKilduff** [comment]
This is limited information to diagnose on, but my first suggestion would be making sure origincap is installed server-side and you are opped on the server. 

If it is neither of those could you provide a log from the server?

**Comment by Cyther-Wuz-Taken** [comment]
I made a quick single player world before I put it on my server to test how the commands work. Does this mod only work on servers?

**Comment by ChristianKilduff** [comment]
yes it only works on servers

**Comment by Cyther-Wuz-Taken** [comment]
Alright I'll try it out on my server later today. Can I do the commands with OP in game or does it have to be done through the server terminal?

**Comment by ChristianKilduff** [comment]
op works fine
