### ISSUE TITLE
SinglePlayer Support

### ISSUE THREAD

**Issue by LJPCODESTUDIO** [WanderingCat27/Origin-Cap#9]
Hey, I'm getting an "awaiting server response" message on the origin selection menu in a singleplayer world.

Version: 1.20.1 Fabric
Log: https://mclo.gs/UthFARG

**Comment by ChristianKilduff** [comment]
> Hey, I'm getting an "awaiting server response" message on the origin selection menu in a singleplayer world.
> 
> 
> 
> Version: 1.20.1 Fabric
> 
> Log: https://mclo.gs/UthFARG

is it messing with your ability to choose origins in singleplayer? in previous versions I disabled the mod in singleplayer worlds

**Comment by LJPCODESTUDIO** [comment]
> is it messing with your ability to choose origins in singleplayer? in previous versions I disabled the mod in singleplayer worlds

Yeah, it completely disables choosing origins. You can't click the select button

**Comment by ChristianKilduff** [comment]
> > is it messing with your ability to choose origins in singleplayer? in previous versions I disabled the mod in singleplayer worlds
> 
> 
> 
> Yeah, it completely disables choosing origins. You can't click the select button

that sounds rlly annoying to break singleplayer ill take a look when i have a chance later. I specifically made sure singleplayer worked at some point in dev, but mightve disapeared at some point while rewriting.

**Comment by LJPCODESTUDIO** [comment]
> that sounds rlly annoying to break singleplayer ill take a look when i have a chance later. I specifically made sure singleplayer worked at some point in dev, but mightve disapeared at some point while rewriting.

Alright, thanks!

**Comment by ChristianKilduff** [comment]
new version in releases of github (not yet on curse/modrinth). Ty for mentioning this, wish this was mentioned sooner. Not actively using or working on this project, but that kind of bug would be very annoying to put up with.

**Comment by LJPCODESTUDIO** [comment]
Great, it worked. Thanks!

**Comment by JadeJuno** [comment]
Shouldn't this issue be closed??-
